### ISSUE TITLE
Using mix configuration to make replaces.exs file configureable.

### ISSUE THREAD

**Issue by h4cc** [h4cc/slugger#1]

**Comment by h4cc** [comment]
Added this so far:

``` elixir
  # File that contains the char replacements.
  @replacement_file "replacements.exs"
```

**Comment by fahrradflucht** [comment]
What exactly do you mean by "using mix configuration"? I first thought you mean [something like this](http://elixir-lang.org/getting-started/mix-otp/distributed-tasks-and-configuration.html#application-environment-and-configuration). But doing it that way, e.g. like so:

``` elixir
  def application do
    [applications: [],
     env: [replacement_file: "replacements.exs"]]
  end
```

won't work since we need the name of the replacement file at compiletime and to access environment configurations set in mix.exs the applications needs to be started.

The alternative is to get the filename out of config.exs like I did here https://github.com/Fahrradflucht/slugger/commit/31555c143d187f809003b809d20c22370b5df577.

**Comment by h4cc** [comment]
Thank your very much! This is what i was looking over a year ago :+1:
