### ISSUE TITLE
Using mix configuration to make default seperator '-' changeable.

### ISSUE THREAD

**Issue by h4cc** [h4cc/slugger#2]

**Comment by h4cc** [comment]
Added this so far:

``` elixir
  # Default char separating
  @separator_char ?-
```

**Comment by fahrradflucht** [comment]
I think the same question as in #1 applies here. Do you want to be able to set separator in `mix.exs`? The difference is that here it would be possible to move the check against the separator into the `replace_chars/1` and the `slugify(_downcase)/2` methods, but I'm not sure about the benefits.

Otherwise we could easily move the config into config.exs like I mentioned in #1. In the end it's just a default and the method takes the separator as an argument.

**Comment by h4cc** [comment]
Thank your very much! This is what i was looking over a year ago :+1:
