### ISSUE TITLE
ö is a problem in Turkish

### ISSUE THREAD

**Issue by max4all** [h4cc/slugger#20]
`ö` is not included in Turkish so it uses German `ö` which translates as `oe`. It should be `o`.

**Comment by fahrradflucht** [comment]
With the current setup there is not much the project can do to solve this. The [`replacements.exs` file](https://github.com/h4cc/slugger/blob/master/lib/replacements.exs) can only provide one replacement for a given character.

But because in many cases you will either need to support German OR Turkish and not both, you can specify your own replacement catalogue in your config like described [here](https://github.com/h4cc/slugger#configuration).

There is possibly a way for slugger to support multiple replacement sets I guess, though. Do you need German and Turkish and know which language it will be ahead of slugifying?

**Comment by max4all** [comment]
One more question. I want to generate 2 slugs, one with asci characters only, and the other with special characters. You said I could use multiple replacement sets. Do you have anything in your mind to achieve that? Thanks
